FROM golang:1.20.2 AS goose
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.9.0

FROM python:3.8
COPY --from=goose /go/bin/goose /usr/local/bin/

RUN pip install tox

COPY . /app
WORKDIR /app

CMD /app/wait-for-postgres.sh tox