FROM golang:1.20.2 AS goose
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.9.0

FROM python:3.11
COPY --from=goose /go/bin/goose /usr/local/bin/

ADD services/__init__.py /root/services/__init__.py
ADD services/utils /root/services/utils
ADD services/migration_service /root/services/migration_service
ADD setup.py setup.cfg /root/
WORKDIR /root
RUN pip install --editable .
CMD migration_service