FROM python:3.11.7-bookworm

RUN apt-get update -y \
    && apt-get -y install libpq-dev gcc

ADD services/__init__.py /src/services/
ADD services/data /src/services/data
ADD services/utils /src/services/utils
ADD services/metadata_service /src/services/metadata_service
ADD setup.py setup.cfg /src/
WORKDIR /src
RUN pip install --editable .

WORKDIR /tmp
USER 1001

CMD metadata_service